// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCapfcHOYUzDpdsSmIDFYW-2b_sgPOzjI4',
    appId: '1:894994812233:web:9ea2b2c4e1421f01ee5e98',
    messagingSenderId: '894994812233',
    projectId: 'act5-login-app',
    authDomain: 'act5-login-app.firebaseapp.com',
    storageBucket: 'act5-login-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRkYsQP2fITnwODIa539NAozWS-Q2HMLQ',
    appId: '1:894994812233:android:66aaa0d9963d0221ee5e98',
    messagingSenderId: '894994812233',
    projectId: 'act5-login-app',
    storageBucket: 'act5-login-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUW5MYGemDE_ltLZLKLscaRBwKZT1pPUs',
    appId: '1:894994812233:ios:46489b66c2c07f77ee5e98',
    messagingSenderId: '894994812233',
    projectId: 'act5-login-app',
    storageBucket: 'act5-login-app.firebasestorage.app',
    iosBundleId: 'com.example.act5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUW5MYGemDE_ltLZLKLscaRBwKZT1pPUs',
    appId: '1:894994812233:ios:46489b66c2c07f77ee5e98',
    messagingSenderId: '894994812233',
    projectId: 'act5-login-app',
    storageBucket: 'act5-login-app.firebasestorage.app',
    iosBundleId: 'com.example.act5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCapfcHOYUzDpdsSmIDFYW-2b_sgPOzjI4',
    appId: '1:894994812233:web:85cc7ec082cc2bfaee5e98',
    messagingSenderId: '894994812233',
    projectId: 'act5-login-app',
    authDomain: 'act5-login-app.firebaseapp.com',
    storageBucket: 'act5-login-app.firebasestorage.app',
  );
}
